# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('split_bills_app', '0004_bill_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(default=False, max_length=200, null=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.RemoveField(
            model_name='paygroup',
            name='members',
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name_plural': 'Bills'},
        ),
        migrations.AddField(
            model_name='bill',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='split_bills_app.Group'),
        ),
        migrations.AlterModelTable(
            name='bill',
            table='bills',
        ),
        migrations.DeleteModel(
            name='PayGroup',
        ),
    ]
