# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_bills_app', '0005_auto_20170221_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
