# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_bills_app', '0006_auto_20170221_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'customusers',
                'verbose_name_plural': 'CustomUsers',
            },
        ),
    ]
