# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split_bills_app', '0007_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='username',
        ),
    ]
