# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split_bills_app', '0008_auto_20170311_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
