# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split_bills_app', '0010_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
    ]
