# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('split_bills_app', '0011_remove_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_paid_by', to='split_bills_app.CustomUser'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='split_between',
            field=models.ManyToManyField(to='split_bills_app.CustomUser'),
        ),
    ]
