# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_bills_app', '0012_auto_20170312_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='added_on',
            field=models.DateField(null=True),
        ),
    ]
